### ISSUE TITLE
Deletion of parent gameobject does not delete children

### ISSUE THREAD

**Issue by jakeandreoli** [donutteam/jeffs-map-creator#12]
**Describe the bug**
When you delete a parent gameobject, it does not delete the children with it. Instead, they get scattered throughout the scene hierarchy.

**To Reproduce**
1. Create an empty game object
2. Create another empty game object
3. Move it inside of the first empty game object
4. Delete the parent

**Expected behavior**
Deleting the parent should delete any children

**Screenshots**
N/A

**Game/Mod Information (please complete the following information):**
 - Tool Version: v0.3
 - P3D Editor Version: N/A
 
**DxDiag (This gives me system specs):**
N/A

**Additional context**
N/A

**Comment by mazexz7** [comment]
Alternatively to this, maybe you could have both `Delete` and  `Delete but keep children` in case the user just wants to keep them around?
I can't think of a situation in which keeping children would be needed, but who knows.

**Comment by TheButterApple24** [comment]
I thought I commented on this haha. Yeah I wanna do what Maz suggested just in-case the user wants to keep the child objects!

**Comment by TheButterApple24** [comment]
In latest version: 0.4!
