### ISSUE TITLE
The program crashes and closes automatically when creating a GameObject, a locator or a collision

### ISSUE THREAD

**Issue by NeoFlixVegas** [donutteam/jeffs-map-creator#8]
**Describe the bug**
This error always appears to me, no matter if you have created a new project or load an old project. You start the project without problems, with the resources you have to make your map (3D models, textures, shaders), but the error happens to me when you create a GameObject, any locator or a collision. In adding a GameObject, at first there is no problem when creating it recently, but when you open it to adjust its rotation, location, add component, the program crashes and closes automatically. With adding a locator or a collision, the program will crash and exit the moment I created it.

**To Reproduce**
1. Open the program.
2. Create a project or load existing project.
3. You create GameObject, a locator or a collision.
4. If you try to open the GameObject to configure or add a component, it will crash and close itself. Creating any locator or a collision will fail and close automatically.

**Expected behavior**
I would like to be able to create a GameObject, a locator or a collision without problems or crashes, to make my desired map to ".p3d"

**Game/Mod Information (please complete the following information):**
 - Version 0.1
 - Version 4 (Pure 3D Editor)
 
**DxDiag (This gives me system specs):**
[DxDiag.txt](https://github.com/donutteam/jeffs-map-creator/files/10299422/DxDiag.txt)

**Additional context**
[Butter.log](https://github.com/donutteam/jeffs-map-creator/files/10299423/Butter.log)

**Comment by TheButterApple24** [comment]
Should be fixed in latest version
